# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  required_plugins = %w( vagrant-vbguest vagrant-disksize )
    _retry = false
    required_plugins.each do |plugin|
        unless Vagrant.has_plugin? plugin
            system "vagrant plugin install #{plugin}"
            _retry=true
        end
    end

    if (_retry)
        exec "vagrant " + ARGV.join(' ')
    end

    config.vm.define "bravetoolsvm" do |bravetoolsvm|
        bravetoolsvm.vm.box = "ubuntu/bionic64"
        bravetoolsvm.disksize.size = "10GB"
        bravetoolsvm.vm.network :private_network, ip: "100.0.0.20"
        bravetoolsvm.vm.hostname = "bravetoolsvm"

        # Remote LXD port
        bravetoolsvm.vm.network "forwarded_port", guest: 8443, host: 8443
        # App port
        bravetoolsvm.vm.network "forwarded_port", guest: 8088, host: 8088
        bravetoolsvm.vm.network "forwarded_port", guest: 3000, host: 3000

        bravetoolsvm.vm.provider "virtualbox" do |vb|
            vb.name = "bravedev"
            vb.memory = "3072"
            vb.cpus = 2
        end
        bravetoolsvm.vm.synced_folder "../.", "/home/vagrant/workspace/src/github.com/bravetools/bravetools"
        
        bravetoolsvm.vm.provision :shell, :privileged => false, :path => "bootstrap.sh"
    end
end